#!/usr/bin/env bash
# Avalhla shared runtime ownership.
# Source this file; do not execute it directly.

if [[ -n "${AVA_RUNTIME_LOADED:-}" ]]; then
    return 0
fi
AVA_RUNTIME_LOADED=1

AVA_ROOT="${AVA_ROOT:-$HOME/Avalhla}"

if [[ -L "$HOME/.ai-memory" ]]; then
    AVA_MEMORY_DIR="${AVA_MEMORY_DIR:-$(readlink -f "$HOME/.ai-memory")}"
else
    AVA_MEMORY_DIR="${AVA_MEMORY_DIR:-$AVA_ROOT/memory}"
fi

AVA_SCRIPTS_DIR="${AVA_SCRIPTS_DIR:-$AVA_ROOT/scripts}"
OLLAMA_HOST="${OLLAMA_HOST:-http://localhost:11434}"

AVA_MODEL="${AVA_MODEL:-${AVALHLA_MODEL:-avalhla}}"
AVA_CHAT_MODEL="${AVA_CHAT_MODEL:-avalhla-chat}"
AVA_CODE_MODEL="${AVA_CODE_MODEL:-avalhla-code}"
AVA_REVIEW_MODEL="${AVA_REVIEW_MODEL:-avalhla-review}"

AVA_CONVERSATIONS_DIR="${AVA_CONVERSATIONS_DIR:-$AVA_MEMORY_DIR/conversations}"
AVA_REFLECTIONS_DIR="${AVA_REFLECTIONS_DIR:-$AVA_MEMORY_DIR/reflections}"
AVA_REVIEWED_DIR="${AVA_REVIEWED_DIR:-$AVA_MEMORY_DIR/reviewed}"
AVA_KNOWLEDGE_DIR="${AVA_KNOWLEDGE_DIR:-$AVA_MEMORY_DIR/knowledge-base}"
AVA_AUTOREAD_DIR="${AVA_AUTOREAD_DIR:-$AVA_MEMORY_DIR/auto-read}"
AVA_PROFILES_DIR="${AVA_PROFILES_DIR:-$AVA_MEMORY_DIR/profiles}"
AVA_REALITY_DIR="${AVA_REALITY_DIR:-$AVA_MEMORY_DIR/reality}"

export AVA_ROOT AVA_MEMORY_DIR AVA_SCRIPTS_DIR OLLAMA_HOST
export AVA_MODEL AVA_CHAT_MODEL AVA_CODE_MODEL AVA_REVIEW_MODEL
export AVA_CONVERSATIONS_DIR AVA_REFLECTIONS_DIR AVA_REVIEWED_DIR
export AVA_KNOWLEDGE_DIR AVA_AUTOREAD_DIR AVA_PROFILES_DIR AVA_REALITY_DIR
